<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA2UxUIE\srcShopware_Production_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA2UxUIE/srcShopware_Production_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerA2UxUIE.legacy');

    return;
}

if (!\class_exists(srcShopware_Production_KernelProdContainer::class, false)) {
    \class_alias(\ContainerA2UxUIE\srcShopware_Production_KernelProdContainer::class, srcShopware_Production_KernelProdContainer::class, false);
}

return new \ContainerA2UxUIE\srcShopware_Production_KernelProdContainer([
    'container.build_hash' => 'A2UxUIE',
    'container.build_id' => '3c7cb19a',
    'container.build_time' => 1587663807,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA2UxUIE');
