<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4sv4Dxn\srcShopware_Production_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4sv4Dxn/srcShopware_Production_KernelProdContainer.php') {
    touch(__DIR__.'/Container4sv4Dxn.legacy');

    return;
}

if (!\class_exists(srcShopware_Production_KernelProdContainer::class, false)) {
    \class_alias(\Container4sv4Dxn\srcShopware_Production_KernelProdContainer::class, srcShopware_Production_KernelProdContainer::class, false);
}

return new \Container4sv4Dxn\srcShopware_Production_KernelProdContainer([
    'container.build_hash' => '4sv4Dxn',
    'container.build_id' => '6b1d0b7b',
    'container.build_time' => 1587663740,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4sv4Dxn');
